name: Validate JSON
on: [push, pull_request]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ajv-cli
        run: npm install -g ajv-cli
      - name: Validate JSON
        run: ajv validate -s schema.json -d data.json